import { EditableText } from '../../../websiteEditor/inline/EditableText'
import type { DateContent, DressCodeContent, FaqContent, GalleryContent, HeroContent, PeopleContent, ResolvedWebsiteMedia, RsvpContent, ScheduleContent, StoryContent, VenueContent } from '../../../websiteEditor/types'

export function ClassicFilipinianaHero({ sectionId, eventName, content }: { sectionId: string; eventName: string; content: HeroContent }) {
  return <div data-section-content className="relative flex min-h-[34rem] flex-col items-center justify-center overflow-hidden px-8 py-24 text-center">
    <div className="absolute inset-5 border border-[color-mix(in_srgb,var(--cf-accent)_30%,transparent)]" /><div className="absolute left-1/2 top-14 h-px w-20 -translate-x-1/2 bg-[var(--cf-accent)]" />
    <p className="relative text-[10px] font-semibold uppercase tracking-[0.38em] text-[var(--cf-secondary)]">Together with their families</p>
    <h1 data-section-heading className="relative mt-7 w-full max-w-2xl font-[family-name:var(--cf-heading-font)] text-5xl leading-[1.05] text-[var(--cf-text)] sm:text-6xl"><EditableText sectionId={sectionId} path={['headline']} value={content.headline} fallback={eventName} showFallbackInEditor placeholder="Add headline" label="Hero headline" /></h1>
    <p data-section-body className="relative mt-6 w-full max-w-lg text-sm leading-7 text-[var(--cf-muted)]"><EditableText sectionId={sectionId} path={['subheadline']} value={content.subheadline} placeholder="Add subheadline" label="Hero subheadline" multiline /></p>
    <div className="relative mt-10 text-2xl text-[var(--cf-accent)]">âœ¦</div>
  </div>
}

export function ClassicFilipinianaDate({ sectionId, date, content }: { sectionId: string; date: string | null; content: DateContent }) {
  return <ContentSection eyebrow="Save the date" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Our Wedding Day" placeholder="Add heading" label="Date heading" />}><p className="font-[family-name:var(--cf-heading-font)] text-2xl text-[var(--cf-text)]">{date ?? 'Date to be announced'}</p><p className="mt-4"><EditableText sectionId={sectionId} path={['description']} value={content.description} placeholder="Add description" label="Date description" multiline /></p></ContentSection>
}

export function ClassicFilipinianaStory({ sectionId, content }: { sectionId: string; content: StoryContent }) {
  return <ContentSection eyebrow="Our journey" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Our Story" placeholder="Add heading" label="Story heading" />}><p className="mx-auto max-w-2xl whitespace-pre-line leading-8"><EditableText sectionId={sectionId} path={['body']} value={content.body} fallback="A story worth celebrating, shared with the people who matter most." placeholder="Add story" label="Story body" multiline /></p></ContentSection>
}

export function ClassicFilipinianaSchedule({ sectionId, content }: { sectionId: string; content: ScheduleContent }) {
  return <ContentSection eyebrow="The celebration" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Schedule" placeholder="Add heading" label="Schedule heading" />}>{content.items.length ? <ol className="mx-auto max-w-xl text-left">{content.items.map((item, index) => <li className="grid grid-cols-[6rem_1fr] gap-4 border-t border-[color-mix(in_srgb,var(--cf-border)_25%,transparent)] py-5" key={index}><span className="text-xs font-semibold uppercase tracking-wider text-[var(--cf-accent)]"><EditableText sectionId={sectionId} path={['items', index, 'time']} value={item.time} fallback="Time TBA" placeholder="Add time" label={`Schedule item ${index + 1} time`} /></span><div><h3 className="font-[family-name:var(--cf-heading-font)] text-xl text-[var(--cf-text)]"><EditableText sectionId={sectionId} path={['items', index, 'title']} value={item.title} fallback="Celebration detail" placeholder="Add title" label={`Schedule item ${index + 1} title`} /></h3><p className="mt-1 text-sm leading-6"><EditableText sectionId={sectionId} path={['items', index, 'description']} value={item.description} placeholder="Add description" label={`Schedule item ${index + 1} description`} multiline /></p></div></li>)}</ol> : <EmptyCopy>Celebration details will appear here.</EmptyCopy>}</ContentSection>
}

export function ClassicFilipinianaVenue({ sectionId, content }: { sectionId: string; content: VenueContent }) {
  return <ContentSection eyebrow="Where to gather" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Venue" placeholder="Add heading" label="Venue heading" />}><p className="font-[family-name:var(--cf-heading-font)] text-2xl text-[var(--cf-text)]"><EditableText sectionId={sectionId} path={['name']} value={content.name} fallback="Venue details to follow" placeholder="Add venue name" label="Venue name" /></p><p className="mt-2 text-sm uppercase tracking-wider text-[var(--cf-muted)]"><EditableText sectionId={sectionId} path={['address']} value={content.address} placeholder="Add address" label="Venue address" multiline /></p><p className="mx-auto mt-5 max-w-xl whitespace-pre-line"><EditableText sectionId={sectionId} path={['description']} value={content.description} placeholder="Add description" label="Venue description" multiline /></p></ContentSection>
}

export function ClassicFilipinianaDressCode({ sectionId, content }: { sectionId: string; content: DressCodeContent }) {
  return <ContentSection eyebrow="What to wear" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Dress Code" placeholder="Add heading" label="Dress code heading" />}><p className="mx-auto max-w-xl whitespace-pre-line leading-8"><EditableText sectionId={sectionId} path={['description']} value={content.description} fallback="Attire guidance will be shared here." placeholder="Add description" label="Dress code description" multiline /></p></ContentSection>
}

export function ClassicFilipinianaPeople({ sectionId, content, mode, media, showMedia }: { sectionId: string; content: PeopleContent; mode: 'editor' | 'public'; media: Record<string, ResolvedWebsiteMedia>; showMedia: boolean }) {
  const groups = content.groups.filter((group) => group.people.length > 0)
  return <ContentSection eyebrow="Those beside us" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Wedding Party" placeholder="Add heading" label="Wedding Party heading" />}>
    {groups.length > 0 ? <div className="mx-auto grid max-w-4xl gap-x-10 gap-y-10 sm:grid-cols-2">{groups.map((group) => <section className="border-t border-[color-mix(in_srgb,var(--cf-border)_30%,transparent)] pt-5" key={group.id}>
      <h3 className="font-[family-name:var(--cf-heading-font)] text-xl text-[var(--cf-text)]">{group.name}</h3>
      <ul className={`mt-4 ${showMedia && group.people.some((person) => person.media && media[person.media.assetId]) ? 'grid grid-cols-2 gap-5' : 'space-y-3'}`}>{group.people.map((person) => { const asset = showMedia && person.media ? media[person.media.assetId] : undefined; const point = person.media?.focalPoint ?? { x: 0.5, y: 0.5 }; return <li key={person.id}>{asset && <img className="mx-auto mb-3 aspect-square w-full max-w-28 rounded-full object-cover" style={{ objectPosition: `${point.x * 100}% ${point.y * 100}%` }} src={asset.web.url} alt="" />}<span className="text-base text-[var(--cf-text)]">{person.name}</span>{person.role && <span className="mt-0.5 block text-[10px] font-semibold uppercase tracking-[0.2em] text-[var(--cf-accent)]">{person.role}</span>}</li> })}</ul>
    </section>)}</div> : mode === 'editor' ? <EmptyCopy>Add groups and people from the Content panel.</EmptyCopy> : null}
  </ContentSection>
}

export function ClassicFilipinianaGallery({ sectionId, content, mode }: { sectionId: string; content: GalleryContent; mode: 'editor' | 'public' }) {
  return <ContentSection eyebrow="Memories" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Gallery" placeholder="Add heading" label="Gallery heading" />}>{mode === 'editor' && <div className="mx-auto grid max-w-xl grid-cols-3 gap-3" aria-label="Empty gallery preview"><div className="aspect-[4/5] border border-dashed border-[var(--cf-border)] bg-[color-mix(in_srgb,var(--cf-surface)_65%,transparent)]" /><div className="flex aspect-[4/5] items-center justify-center border border-dashed border-[var(--cf-border)] bg-[var(--cf-surface)] px-2 text-xs text-[var(--cf-muted)]">Photos will appear here</div><div className="aspect-[4/5] border border-dashed border-[var(--cf-border)] bg-[color-mix(in_srgb,var(--cf-surface)_65%,transparent)]" /></div>}</ContentSection>
}

export function ClassicFilipinianaFaq({ sectionId, content }: { sectionId: string; content: FaqContent }) {
  return <ContentSection eyebrow="Good to know" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Frequently Asked Questions" placeholder="Add heading" label="FAQ heading" />}>{content.items.length ? <div className="mx-auto max-w-2xl text-left">{content.items.map((item, index) => <div className="border-t border-[color-mix(in_srgb,var(--cf-border)_25%,transparent)] py-5" key={index}><h3 className="font-[family-name:var(--cf-heading-font)] text-lg text-[var(--cf-text)]"><EditableText sectionId={sectionId} path={['items', index, 'question']} value={item.question} fallback="Question" placeholder="Add question" label={`FAQ ${index + 1} question`} /></h3><p className="mt-2 whitespace-pre-line text-sm leading-6"><EditableText sectionId={sectionId} path={['items', index, 'answer']} value={item.answer} placeholder="Add answer" label={`FAQ ${index + 1} answer`} multiline /></p></div>)}</div> : <EmptyCopy>Helpful details will appear here.</EmptyCopy>}</ContentSection>
}

export function ClassicFilipinianaRsvp({ sectionId, content }: { sectionId: string; content: RsvpContent }) {
  return <ContentSection eyebrow="Celebrate with us" heading={<EditableText sectionId={sectionId} path={['heading']} value={content.heading} fallback="Kindly Respond" placeholder="Add heading" label="RSVP heading" />}><p className="mx-auto max-w-lg whitespace-pre-line"><EditableText sectionId={sectionId} path={['description']} value={content.description} fallback="We would be honored to celebrate this day with you." placeholder="Add description" label="RSVP description" multiline /></p><div data-rsvp-button className="mx-auto mt-8 max-w-xs border border-[var(--cf-theme-accent)] bg-[var(--cf-theme-accent)] px-7 py-3 text-xs font-semibold uppercase tracking-[0.18em] text-white"><EditableText sectionId={sectionId} path={['buttonLabel']} value={content.buttonLabel} fallback="RSVP" placeholder="Add button label" label="RSVP button label" /></div></ContentSection>
}

function ContentSection({ eyebrow, heading, children }: { eyebrow: string; heading: React.ReactNode; children: React.ReactNode }) { return <div data-section-content className="px-7 py-20 text-center sm:px-12"><p className="text-[10px] font-semibold uppercase tracking-[0.32em] text-[var(--cf-secondary)]">{eyebrow}</p><h2 data-section-heading className="mx-auto mt-3 w-full max-w-2xl font-[family-name:var(--cf-heading-font)] text-3xl text-[var(--cf-text)] sm:text-4xl">{heading}</h2><div data-section-body className="mx-auto mt-8 text-sm leading-7 text-[var(--cf-muted)]">{children}</div></div> }
function EmptyCopy({ children }: { children: React.ReactNode }) { return <p className="italic text-[var(--cf-muted)]">{children}</p> }
